/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java Library project to get you started.
 * For more details take a look at the Java Libraries chapter in the Gradle
 * user guide available at https://docs.gradle.org/4.7-rc-2/userguide/java_library_plugin.html
 */

plugins {
    `java-gradle-plugin`
    `kotlin-dsl`
    `maven-publish`
    `groovy`
}

group = "me.champeau.gradle"
version = "1.0"

gradlePlugin {
    (plugins) {
        "brokenBomPlugin" {
            id = "me.champeau.bubble-bom"
            implementationClass = "me.champeau.gradle.bom.BubbleBomPlugin"
        }
    }
}

repositories {
    jcenter()
}

dependencies {
    testCompile(gradleTestKit())
    testCompile("org.spockframework:spock-core:1.0-groovy-2.4") {
        exclude("org.codehaus.groovy", "groovy-all")
    }
}

publishing {
    repositories {
        maven(url = "build/repository")
    }
}